# GitHub Pages Configuration
title: "Energy Management System"
description: "Smart Billing Management System with English Default"
baseurl: ""
url: "https://moss-xxh.github.io/Techno-Meters-web"

# Build settings
markdown: kramdown
highlighter: rouge

# Include/Exclude files
include:
  - assets

exclude:
  - README.md
  - deploy.sh

# GitHub Pages specific settings
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter

# Relative links settings
relative_links:
  enabled: true
  collections: false

# Optional front matter
optional_front_matter:
  remove_originals: false